/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xiaonei.web.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.xiaonei.domain.Users;
import com.xiaonei.service.inter.UserServiceInter;
import com.xiaonei.web.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 10-17-2016
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="userForm" parameter="flag" scope="request"
 */
public class LoginAction extends DispatchAction {
	
	private UserServiceInter userService;
	
	public void setUserService(UserServiceInter userService) {
		this.userService = userService;
	}

	
	//注销用户
	public ActionForward logout(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//把当前网站session清空
		request.getSession().invalidate();
		return mapping.findForward("goIndexUI");
	}
	
	//响应用户登录请求
	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm = (UserForm) form;// TODO Auto-generated method stub
		
		//通过登录表单取出用户输入的电子邮箱和密码，然后到数据库去验证
		//第一种方案：[分析：从mvc角度看，不推荐这种做法， MVC action是c角色，因此应当尽可能的把业务逻辑写到service中去]
//		userService.getResult
//		("from Users where email=? and pwd=?", new Object[]{userForm.getEmail(),userForm.getPwd()});
		
		
		//第二种方案：将业务逻辑放在service
		Users user = new Users();
		user.setEmail(userForm.getEmail());  //把用户登录的表单中的数据取出来放在user对象中，然后去验证这个对象
		user.setPwd(userForm.getPwd());
		user = userService.check(user);
		if(user!=null){
			//用户合法，必须把该用户bean放入session域对象
			request.getSession().setAttribute("loginuser", user);			
			return mapping.findForward("goHomeUI");
		}else{
			//用户不合法
			return mapping.findForward("goIndexUI");
		}
	}
}