/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xiaonei.web.action;

import java.sql.Timestamp;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.xiaonei.domain.University;
import com.xiaonei.domain.Users;
import com.xiaonei.domain.Useruniversity;
import com.xiaonei.service.inter.CountryServiceInter;
import com.xiaonei.service.inter.ProvinceServiceInter;
import com.xiaonei.service.inter.UniversityServiceInter;
import com.xiaonei.service.inter.UserServiceInter;
import com.xiaonei.service.inter.UseruniversityServiceInter;
import com.xiaonei.web.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-29-2016
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class RegisterAction extends DispatchAction {
	

	private CountryServiceInter countryService;
	private ProvinceServiceInter provinceService;
	private UniversityServiceInter universityService;
	private UserServiceInter userService;
	private UseruniversityServiceInter useruniversityService;
	
	public UseruniversityServiceInter getUseruniversityService() {
		return useruniversityService;
	}

	public void setUseruniversityService(
			UseruniversityServiceInter useruniversityService) {
		this.useruniversityService = useruniversityService;
	}

	public UserServiceInter getUserService() {
		return userService;
	}

	public void setUserService(UserServiceInter userService) {
		this.userService = userService;
	}

	public UniversityServiceInter getUniversityService() {
		return universityService;
	}

	public void setUniversityService(UniversityServiceInter universityService) {
		this.universityService = universityService;
	}

	public ProvinceServiceInter getProvinceService() {
		return provinceService;
	}

	public void setProvinceService(ProvinceServiceInter provinceService) {
		this.provinceService = provinceService;
	}

	public CountryServiceInter getCountryService() {
		return countryService;
	}

	public void setCountryService(CountryServiceInter countryService) {
		this.countryService = countryService;
	}

	//跳转到注册页面
	public ActionForward regUI(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		//准备数据，供用户选择大学的时候使用
		//国家
		request.setAttribute("countrylist", countryService.getResult("from Country", null));
		
		
		//省和直辖市（默认中国的）
		request.setAttribute("provincelist", provinceService.getResult
				("from Province where country.id=?", new Object[]{new Integer(1)}));
		//大学的名字（默认显示北京的）
		request.setAttribute("unilist", universityService.getResult
				("from University where province.id=? and country.id=?", new Object[]{new Integer(1),new Integer(1)}));
		
		//注册成功则跳转到home.jsp页面
		return mapping.findForward("regUI");
	}
	
	//注册用户,真正的添加到数据库中
	public ActionForward regUser(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//从该action对应的表单中取出数据
		UserForm userForm = (UserForm)form;
		
		//需要把取出的信息保存到一个user对象中
		Users user = new Users();
		
		user.setEmail(userForm.getEmail());
		user.setLoginDate(new java.util.Date());
		user.setName(userForm.getName());
		user.setPwd(userForm.getPwd());
		user.setRegisterDate(new java.util.Date());
		user.setSex(userForm.getSex());		
		
		//需要根据注册提交过来的大学id查出是哪所大学：
		University university = (University) universityService.findById(University.class, Integer.valueOf(userForm.getUniversityId()));
		
		//还要创建该对应的用户大学记录
		Useruniversity useruniversity = new Useruniversity();
		useruniversity.setUsers(user);  //首先需要把上面的用户添加到用户大学里
		useruniversity.setUniversity(university);
		useruniversity.setUserType(userForm.getUserType());
		
		//保存用户
		userService.save(user);
		useruniversityService.save(useruniversity);
		
		//注册成功则跳转到home.jsp页面
		return mapping.findForward("regok");
	}
}